### ISSUE TITLE
setAdapter not working for androidx.recyclerview

### ISSUE THREAD

**Issue by ngallazzi** [gotev/recycler-adapter#3]
setAdapter method does not work anymore with new androidx RecyclerView. 

setAdapter (androidx.recyclerview.widget.RecyclerView.Adapter) in RecyclerView cannot be applied to
(net.gotev.recycleradapter.RecyclerAdapter)

**Comment by gotev** [comment]
It's a known issue because the library has not been updated yet to support AndroidX. Are you willing to help by adding it and sending a PR? I will be glad to provide guidance if needed.

**Comment by ngallazzi** [comment]
Sure thing! I tried to fork and clone the repository but when I open it in android studio I can't see the app module. Is there something in particular I need to know about?

**Comment by gotev** [comment]
Sure! Open the project which is in the app directory from Android Studio. It will open the demo project with the recycler adapter module in it. Then you can do all the needed refactorings and updates. Once it compiles and it works when run, it's done. Feel free to update all the dependencies and SDK targets to the latest versions available today.

**Comment by gotev** [comment]
Version `1.8.0` with support for AndroidX released! Cheers @ngallazzi you are in the README credits, too. Thanks for the help!

**Comment by Chilijia28** [comment]
Hi mate , what do you mean with version 1.8.0.  Any specific solution to solve the problem ? Sorry I am just a beginner

**Comment by gotev** [comment]
Hi this is an old issue. Follow the readme for the most up to date information and version.

**Comment by kamau-mbugua** [comment]
So being an old issue, I cant get solution to this

```
setAdapter
(androidx.recyclerview.widget.RecyclerView.Adapter)
in RecyclerView cannot be applied
to 
(example.example.com.project.ProductAdapter)
```

[Have Tried This solution to no success](https://stackoverflow.com/questions/36978341/problems-between-adapter-and-array-in-recyclerviewl)

[This is The recommendation from official Docs](https://developer.android.com/reference/androidx/recyclerview/widget/RecyclerView.Adapterl)

**Comment by gotev** [comment]
Use latest 2.8.2. check readme and clone the project and check demo app for example usage. Using it in production without any problems with AndroidX.

**Comment by kamau-mbugua** [comment]
@gotev Oky, Thank you
