### ISSUE TITLE
Sectioned adapter + horizontal Adapter inside Vertical 

### ISSUE THREAD

**Issue by AnthonyKoueik** [gotev/recycler-adapter#9]
Hello 

Can you please make a good practice of how to integrated a solid sectioned list.

Adding an Horizontal scrolling inside a vertical adapter. (Make it smooth)

thank you 

br,

**Comment by gotev** [comment]
Check out the demo app in the develop branch :wink:

**Comment by AnthonyKoueik** [comment]
Hello

I didn't anything related to horizontal scrolling

**Comment by gotev** [comment]
@AnthonyKoueik Clone the `develop` branch. Look at this activity: https://github.com/gotev/recycler-adapter/blob/develop/app/demo/src/main/java/net/gotev/recycleradapterdemo/activities/Carousels.kt

**Comment by gotev** [comment]
This has now been merged and released in `2.4.0`. Docs: https://github.com/gotev/recycler-adapter#carousels
